name: Lint with Ruff

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Detect Default Branch
        id: detect-branch
        run: |
          # Detect the default branch
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
          if [ -z "$DEFAULT_BRANCH" ]; then
            echo "Default branch detection failed. Falling back to 'find-smallest-number'."
            DEFAULT_BRANCH="find-smallest-number"
          fi
          echo "default-branch=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Run Ruff on Modified Files
        run: |
          # Get the default branch from the environment variable
          MODIFIED_FILES=$(git diff --name-only ${{ env.default-branch }} | grep '\.py$')

          # Run Ruff only on modified files
          if [ -n "$MODIFIED_FILES" ]; then
            echo "$MODIFIED_FILES" | xargs ruff check --fix
          else
            echo "No Python files modified in this branch."
          fi
